### ISSUE TITLE
Crash on empty disk images

### ISSUE THREAD

**Issue by mstempell** [ggnkua/Jacknife#1]
When you remove all files from a disk image (either .st or .msa), manipulating the image crashes the plugin.
(and then : in 32bit Total Commander, a memory problem shows up - and in 64bit Total Commander, Total Commander closes)
OS : Windows XP / Windows 10

The disk images have been created with the plugin.

**Comment by ggnkua** [comment]
Hi there,

Sorry for the late response, for some reason I didn't get email notifications (hopefully this will be better now).

I haven't managed to reproduce your crash. So there are a couple of things you could do:

1. Try an updated version I uploaded (but not released) in https://github.com/ggnkua/Jacknife/tree/main/install
2. If that doesn't work, could send me the files you used to create the image? That way I can try to reproduce the crash here. If they are sensitive data you could email me them so they won't show up here. Or in general, if you get it to crash with any files, just tell me the folder structure (are you adding files in the root folder? Or do you use subfolders? etc) and I'll also try to reproduce.
3. Again, if possible, could you send me the actual image that causes the crash if you still have it?

Thanks!

**Comment by mstempell** [comment]
OK it works fine with the updated wip version you pointed at. 👍
On 64bit and 32bit, that is (I retested both contexts).
So your changes fixed it i'd say. Great!

**Comment by ggnkua** [comment]
Good good, closing!
