### ISSUE TITLE
Wrong version reported by install

### ISSUE THREAD

**Issue by mikrosk** [ggnkua/Jacknife#2]
When clicked on the zip file in TC, I was offered to install it but with wrong version being reported? (I grabbed 0.10 at that time)

![image](https://github.com/user-attachments/assets/6ea15b74-6900-40b2-8cbb-1fbd2a6037ac)

**Comment by ggnkua** [comment]
Oh, I must have never changed that text, sorry :(

But it should be the correct version indeed. Probably won't re-release to avoid confusion, but I'll make a note for next version. Thanks for bringing it to my attention!
